### ISSUE TITLE
pages-rails gem

### ISSUE THREAD

**Issue by c-sonnier** [revoxltd/pages-rails-sample#3]
Where is the pages-rails gem? The path in the Gemfile for pages-rails is pointing to a local location: :path => '/Users/malithisuru/Documents/Projects/ace/pages-rails'

**Comment by Svashtar** [comment]
I've bought your template on themeforrest and would also like to know where the gem is?
It is not present in the package, so localy bundling it is not possible, and it is not in your repository.
Is it cancelled? I mean, this was one of the resons i've bought the theme, so I would kindly aks you to let us know what the situation is.

Thank you

**Comment by MalithHatananchchige** [comment]
Hi there

The gem is over here :)

https://github.com/revoxltd/pages-rails/releases/tag/v3.0.0

Download and link it manually, call it via GitHub repo with credentials anything you like.

**Comment by Svashtar** [comment]
I am getting 404, is there a trick to it?

**Comment by MalithHatananchchige** [comment]
Resent an invite to the correct team

**Comment by Svashtar** [comment]
Thx, all good.

**Comment by scriptfans** [comment]
@MalithHatananchchige I've aslo bought your template on themeforrest, can you invite me to the team? thanks.
![image](https://user-images.githubusercontent.com/359790/33542108-9b0da3f8-d90c-11e7-83ea-fce540df02ed.png)

**Comment by MalithHatananchchige** [comment]
@scriptfans please use this page

http://pages.revox.io/dashboard/

To add yourself in :) I have already added you in.
